Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PrettyEmbedYoutube:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PrettyEmbedYoutube: true
  Fusion:
    defaultContext:
      Jonnitto.PrettyEmbedYoutube: 'Jonnitto\PrettyEmbedYoutube\Eel\YoutubeHelper'
  ContentRepository:
    labelGenerator:
      eel:
        defaultContext:
          Jonnitto.PrettyEmbedYoutube: 'Jonnitto\PrettyEmbedYoutube\Eel\YoutubeHelper'
