Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PrettyEmbedYoutube:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PrettyEmbedYoutube: true
