Carbon:
  IncludeAssets:
    Packages:
      'Jonnitto.PrettyEmbedYoutube':
        Package: 'Jonnitto.PrettyEmbedYoutube'
        ConditionPrototype: 'Jonnitto.PrettyEmbedYoutube:IncludeAssets'
        Path:
          File:
            CSS: 'Public'
            JS: 'Public'
        General:
          Head:
            - Main.css
            - Main.js[defer]
        Backend:
          Head: Backend.js[defer]

Jonnitto:
  PrettyEmbedYoutube:
    imgResultion: maxresdefault
    maximumWidth: 1280
    wrapper: false
    embed:
      class: jonnitto-prettyembedyoutube--embed
      video: 'https://www.youtube.com/embed/'
      playlist: 'https://www.youtube.com/embed/videoseries?list='
    lightbox:
      class: jonnitto-prettyembedyoutube--popup
      video: 'https://www.youtube.com/watch?v='
      playlist: 'https://www.youtube.com/playlist?list='
    defaults:
      type: video
      lightbox: false
      allowFullScreen: true
      showinfo: true
      showControls: true
      loop: false
      closedCaptions: false
      showRelated: false

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PrettyEmbedYoutube:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PrettyEmbedYoutube: true
