Jonnitto:
  PrettyEmbedYoutube:
    enableJsApi: false
    url:
      playlist:
        embed: 'https://www.youtube.com/embed/videoseries?list=%id%'
        href: 'https://www.youtube.com/playlist?list=%id%'
      video:
        embed: 'https://www.youtube.com/embed/%id%'
        href: 'https://www.youtube.com/watch?v=%id%'
    defaults:
      # This can be 'video' or 'playlist'. Per default this is set via the node properties
      type: video
      # Should the video be opened on a lightbox? Per default this is set via the node properties
      lightbox: false
      # When the lightbox is set, should the preview image preserve his aspect ratio? Per default this is set via the node properties
      preserveAspectRatio: true
      # If no aspect ratio can be calcualted from the oembed service, you have the possibility to force the aspect ratio 16:9. Per default this is set via the node properties
      force16to9: true
      allowFullScreen: true
      showinfo: false
      controls: true
      loop: false
      closedCaptions: false
      showRelated: false
      playsinline: true
